2017-11-11T04:31:22.8332498-02:00;VSTestExecutionThread;Info;SpecFlow+Runner execution started
2017-11-11T04:31:22.9428294-02:00;VSTestExecutionThread;Info;SpecRun: running tests in D:\Projetos\VALTECH\PointOfSaleTest\PointOfSaleTest\bin\Debug\PointOfSaleTest.dll
2017-11-11T04:31:22.9438475-02:00;VSTestExecutionThread;Info;Profile: Default
2017-11-11T04:31:22.9968662-02:00;Thread#7;Info;Discovering target: Default
2017-11-11T04:31:22.9978721-02:00;Thread#7;Info;Discovering tests from assembly: D:\Projetos\VALTECH\PointOfSaleTest\PointOfSaleTest\bin\Debug\PointOfSaleTest.dll
Appdomain Disposed
Test Suite Dump
#0: PointOfSaleTest/Default - 
#1: Default - 
#2: PointOfSaleTest - 
#3: Categories - 
#4: Add categories - TestAssembly:PointOfSaleTest/Feature:Categories/Scenario:Add+categories
End: Test Suite Dump
Thread#0:Scheduler: get next test for thread 0
Thread#:Scheduler: testitem #4 from normal test queue 
Thread#0:Scheduler: considering testitem #4 for thread 0
Thread#0:TestItem#4:testItemMatchesCurrentTestThread:UnSpecific
Thread#0:TestItem#4:runsOnOneOtherThreadSpecific:False
Thread#0:TestItem#4:runsOnOneOtherThreadUnspecific:False
Thread#0:Scheduler: using testitem #4 for thread 0
Thread#0:Scheduler: Test #4 is scheduled for thread
Thread#0:Scheduler: with testItemExecutionIndex 0
Thread #0: creating new test thread executor for PointOfSaleTest, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null (target: Default)
Loading SpecRun type 'TechTalk.SpecRun.Framework.TestAssemblyExecutor' from: C:\Users\lminu\AppData\Local\Temp\VisualStudioTestExplorerExtensions\SpecRun.Runner.1.6.3\tools\TechTalk.SpecRun.Framework.Executor.dll
Thread#0: Test #4/0 is started on thread #0
Thread#0:T:-> Using app.config
Thread#0:B:Given I have entered a 'description' into the category form
Thread#0:T:error: Uma exceção foi acionada pelo destino de uma chamada.
Thread#0:B:When I press add
Thread#0:T:skipped because of previous errors
Thread#0:B:Then the result should be 'Category added successfully.' on the screen
Thread#0:T:skipped because of previous errors
Thread#0:TestItem#4:Scheduler: reschedule tests for testitem #4
Thread#0:Scheduler: get next test for thread 0
Thread#:Scheduler: dequeuing a rescheduled testitem: #4
Thread#0:Scheduler: considering testitem #4 for thread 0
Thread#0:TestItem#4:testItemMatchesCurrentTestThread:UnSpecific
Thread#0:TestItem#4:runsOnOneOtherThreadSpecific:False
Thread#0:TestItem#4:runsOnOneOtherThreadUnspecific:False
Thread#0:Scheduler: using testitem #4 for thread 0
Thread#0:Scheduler: Test #4 is scheduled for thread
Thread#0:Scheduler: with testItemExecutionIndex 1
Thread#0: Test #4/0 is finished on thread #0 as Failed within 0,1706194 seconds
Thread#0: Test #4/1 is started on thread #0
Thread#0:B:Given I have entered a 'description' into the category form
Thread#0:T:error: Uma exceção foi acionada pelo destino de uma chamada.
Thread#0:B:When I press add
Thread#0:T:skipped because of previous errors
Thread#0:B:Then the result should be 'Category added successfully.' on the screen
Thread#0:T:skipped because of previous errors
Thread#0:Scheduler: get next test for thread 0
Thread#:Scheduler: dequeuing a rescheduled testitem: #4
Thread#0:Scheduler: considering testitem #4 for thread 0
Thread#0:TestItem#4:testItemMatchesCurrentTestThread:UnSpecific
Thread#0:TestItem#4:runsOnOneOtherThreadSpecific:False
Thread#0:TestItem#4:runsOnOneOtherThreadUnspecific:False
Thread#0:Scheduler: using testitem #4 for thread 0
Thread#0:Scheduler: Test #4 is scheduled for thread
Thread#0:Scheduler: with testItemExecutionIndex 2
Thread#0: Test #4/1 is finished on thread #0 as Failed within 0,0060042 seconds
Thread#0: Test #4/2 is started on thread #0
Thread#0:B:Given I have entered a 'description' into the category form
Thread#0:T:error: Uma exceção foi acionada pelo destino de uma chamada.
Thread#0:B:When I press add
Thread#0:T:skipped because of previous errors
Thread#0:B:Then the result should be 'Category added successfully.' on the screen
Thread#0:T:skipped because of previous errors
Thread#0:Scheduler: get next test for thread 0
Thread#:Scheduler: at the end of normal test queue
Thread#0:Scheduler: enumerator for thread is at end
Thread#0:Scheduler: No more tests for thread
Thread#0: Test #4/2 is finished on thread #0 as Failed within 0,0060043 seconds
Appdomain Disposed
Thread#-1:Scheduler: get next test for thread -1
Thread#:Scheduler: at the end of normal test queue
Thread#-1:Scheduler: enumerator for thread is at end
Total: 1 (test executions: 3)
Succeeded: 0
Ignored: 0
Pending: 0
Skipped: 0
Failed: 1
